dc:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: dc-food-express
    username: root
    password: 1234567890
  aws:
    accessKeyId: AKIAVBFCSYIL376WFOI5
    secretKeyId: x1QvGbLCh81WYzoiPOUJTLZ7Z/X8lDX5e2GJQSrE
    bucketName: dc-food-express
    bucketRegion: us-west-2
  redis:
    host: localhost
    port: 6379
    password: 1234567890
    database: 0
